repo_update.sh

fixes this error:
```
git: 'https://android.googlesource.com/platform/bootable/recovery' is not a git command. See 'git --help'.
```

Add missing "fetch"

---

repo_update.sh

It is necessary for the successful compilation and launch of Android 8.1 on our devices. The patches that were added to the Google repository were removed. **All required patches have been updated and can be used.**

[master] Updates for Android 8.1

---

repo_update.sh

These patches do the following:
1. allow loire devices to load audio xmls from /vendor
2. avoid a crash in hwc2 due to failure to init color mode
3. allow loading of firmware files from /odm

o-mr1 patches

---

repo_update.sh

[o-mr0] sony: repo_update: Add patches for new GPS HAL (sdm845)

---

repo_update.sh

This patch reverts
https://android.googlesource.com/platform/system/core/+/1d540dd0f44c1c7d40878f6a7bb447e85e6207ad
which is splitting battery draw
and bring back
https://android-review.googlesource.com/c/platform/system/core/+/469437
which allow current sources to be used as an override.
Although charger is still broken due to init.rc rework but it is necessary
to load sony healthd sources properly.
Signed-off-by: Humberto Borba <humberos@gmail.com>

[android-8.1.0_r3.] system: core: Bring back board overrides in mode_charger

---

repo_update.sh

This update is only for n-mr1 with kernel 4.4. 
Issue is due to https://github.com/sonyxperiadev/kernel/pull/1397 which integrate new-style UID routing from o-mr0.
This PR needs a new branch n-mr1_4.4 to distinguish from other kernel versions.

[N-mr1] Fix network per-UID routing

---

repo_update.sh

loire platform needs this patch so that UBWC flag is not set by gralloc1 for usecases such as screen recording or screen casting.

Add: display patch for UBWC support

---

repo_update.sh

* Before:
HWCColorManager::CreateColorManager: Unable to load = libsdm-disp-apis.so
* After:
HWCColorManager::CreateColorManager: Successfully loaded libsdm-disp-vndapis.so
* Gerrit change: https://android-review.googlesource.com/#/c/platform/hardware/qcom/display/+/645379/

Add display HAL patch that lets us load proper HWCColorManager lib

---

repo_update.sh

* Few of devices that we currently support (pioneer, discovery)
recently enabled support for it however it doesn't work without
platform changes.
* Following changes are required to make it actually work:
https://android-review.googlesource.com/#/c/platform/packages/apps/Nfc/+/666362/
https://android-review.googlesource.com/#/c/platform/system/nfc/+/515517/
https://android-review.googlesource.com/#/c/platform/system/nfc/+/533315/

Add changes required to support NFC extended length

---

repo_update.sh

- Reverts patches in order to cherry-pick 5df73d0
git revert --no-edit 8cede07e698cc1a15257a6b5dd653488e2bbf49e # Revert "Optimizations to abi checking."
git revert --no-edit 0f1bd9d3d73f1d1a673c23d5b180172c8c4605db # Revert "Add arch, lib name to header-abi-diff invocation."
git revert --no-edit e54d01029b8e2743254740a7a2ca167c6647e5d2 # Revert "Add libandroid_net to the llndk."
git revert --no-edit 10b40b087cb9b7ead39da1e9fc6b7a85ecb4a901 # Revert "Fix lots of warnings from abi dumping."
git revert --no-edit 756b1c2343ed019ad59868c81491ea1eb7d42c57 # Revert "Add header-abi-checker for Vndk abi checks."
git revert --no-edit 95421a4a776c5119d7d0729dd2efe05568d19f2b # Revert "Split /system and /vendor modules, allow multi-installation"
git revert --no-edit …

Fix applying build/soong patches

---

repo_update.sh

Add missing cherry-pick on previous commit c740499 :
- git cherry-pick e28f4e2acfcca00766080d294daa75ae2efb5853 # Support test_suites in cc_benchmark modules

Fix soong build after a complete clean

---

repo_update.sh

https://android.googlesource.com/platform/build/+/47ec5ab561bd979560bde402201268486ce9cc34
Build recovery-two-step.img for two-step OTAs.
In two-step OTAs, we write recovery image to /boot as the first step so
that we can reboot from there and install a new recovery image to
/recovery. However, bootloader will show "Your device is corrupt"
message when booting /boot with the recovery image. Because the recovery
image encodes the path of "/recovery" as part of the signature metadata,
which fails the verified boot.
This CL generates a special "recovery-two-step.img" in addition to the
regular recovery.img. This image encodes "/boot" when being signed,
which will be flashed to /boot at stage 1/3 in a two-step OTA.

Add patch for two-step OTAs.

---

repo_update.sh

Added patches:
https://android-review.googlesource.com/c/platform/hardware/qcom/audio/+/708808 Add msm8976 tasha sound card detection to msm8916 HAL
https://android-review.googlesource.com/c/platform/hardware/qcom/audio/+/708809 post_proc: Enable post processing for msm8952
https://android-review.googlesource.com/c/platform/hardware/qcom/audio/+/708810 audio: add support for sdm845 platform
https://android-review.googlesource.com/c/platform/hardware/qcom/bootctrl/+/708811 Replace hardcoded build barier with a generic one
https://android-review.googlesource.com/c/platform/hardware/qcom/display/+/708812 display: add barier for kernel headers
https://android-review.googlesource.com/c/platform/hardware/qcom/display/+/708813 display: remove blob dependency …

Add patches required to build using sdm845 hals and 4.9 kernel headers

---

repo_update.sh

Allow sign_target_files_apks.py to create zip64 signed TF.zip.
- https://android.googlesource.com/platform/build/+/2b8f489e304e1afd7ae607000d5e7022328293db

[8.0.0_r33] Add patch to use zip64 for signing TF.zip

---

repo_update.sh

Allow sign_target_files_apks.py to create zip64 signed TF.zip.
- https://android.googlesource.com/platform/build/+/2b8f489e304e1afd7ae607000d5e7022328293db

[8.0.0_r30] Add patch to use zip64 for signing TF.zip

---

repo_update.sh

Fix path of previous commit. Since Android 8.0, platform/build repository has been moved to build/make so patch has to be applied on it.

[8.0.0_r30] Add patch to use zip64 for signing TF.zip 

---

repo_update.sh

Fix path of previous commit. Since Android 8.0, platform/build repository has been moved to build/make so patch has to be applied on it.

[8.0.0_r33]  Add patch to use zip64 for signing TF.zip

---

repo_update.sh

Allow sign_target_files_apks.py to create zip64 signed TF.zip.
- https://android.googlesource.com/platform/build/+/2b8f489e304e1afd7ae607000d5e7022328293db

[7.1.2_r36] Add patch to use zip64 for signing TF.zip

---

repo_update.sh

Allow sign_target_files_apks.py to create zip64 signed TF.zip.
- https://android.googlesource.com/platform/build/+/2b8f489e304e1afd7ae607000d5e7022328293db

[7.1.1_r55] Add patch to use zip64 for signing TF.zip

---

repo_update.sh

It seems that sdm845 dir was removed between android-p-preview-5 and
pie-release, so I'll leave the relevant patches commented out as reference for
when it's restored.

Adapt hardware/qcom/media patches to Pie

---

repo_update.sh

Currently vold doesn't recognize exfat as supported filesystem.
Picking this patch fixes this issue.
Link: https://android-review.googlesource.com/c/platform/system/vold/+/703124

Add support for exFAT file system to vold

---

repo_update.sh

the initial version was inconsistent with latest 713242 patch version
Apply patchs fails since this commit https://github.com/sonyxperiadev/repo_update/commit/4d4cca0a4723cd8fecebb2f29d23d90b07d0ac89

media: msm8996: bump 713243 patch version

---

repo_update.sh

4.9 kernel introduces a new vidc driver, while keeping the legacy driver.
Unfortunately, the sdm845 media hal only works with the new driver, so old devices need to use the msm8998 media hal.
The msm8998 hal is expecting 4.4 kernel headers though, so it fails compilation on 4.9.
These patches make the hal build with 4.9 kernel headers, allowing legacy devices to have functional vidc.

Add: hardware/qcom/media patches for compatibility with 4.9 kernel

---

repo_update.sh

We used to patch this via https://r.android.com/741001
```
on property:vold.decrypt=trigger_restart_framework
-    stop surfaceflinger
-    start surfaceflinger
exec_start update_verifier
class_start main
class_start late_start
+    setprop service.bootanim.exit 0
+    start bootanim
```
The patch no longer applies since the following patch to system/core was merged into the 2019-07 security patch branches:
@c61ef4: Start update_verifier early in late-fs
https://android.googlesource.com/platform/system/core/+/c61ef4
```
on property:vold.decrypt=trigger_restart_framework
stop surfaceflinger
start surfaceflinger
-    # A/B update verifier that marks a successful boot.
-    exec_start update_verifier
class_start main
class_start late_start
```
Besides, the patch was only ever cosmetic.

Remove system/core bootanimation patch

---

repo_update.sh

With a small local change I was using `git cherry-pick $_commit` all the time, over `git cherry-pick FETCH_HEAD`. This gives a couple `bad object` errors because the commit hashes are accidentally based on the commit _after_ cherry-picking, instead of the hash from the fetched one.
While not fatal in a normal environment, this adjusts the `apply_gerrit_cl_commit` function to warn in such a case, allowing the editor to adjust the hash and making the fetch ever-so-slightly more efficient :grin: 
Pinging @ix5 for review.

Correct commit hashes to fetched ones

---

frameworks/base/0001-Add-camera-key-long-press-handling.patch
hardware/nxp/nfc/0001-hardware-nxp-Restore-pn548-support.patch
hardware/nxp/nfc/0002-hardware-nxp-Restore-pn547-support.patch
hardware/qcom/audio/0001-hal-msm8916-Add-missing-bracket-to-close-function-de.patch
hardware/qcom/bootctrl/0001-Q-Never-build-bootctrl-the-old-way.patch
hardware/qcom/gps/0001-set_sched_policy-was-reverted-but-invocation-still-t.patch
repo_update.sh

Apart the obvious, this contains a bunch of interesting changes:
While it makes _perfect_ sense to fetch patches from AOSP for as long as they are not merged, there's no point in spamming their gerrit with commits that will never get merged _anyway_.
For this reason, a very simple version of local patching has been added. It simply finds and applies (`git am`) all patches found in the same directory structure.
For now, applying all patches at once (with the sorting given by `git format-patch`) is sufficient; may we ever need to intertwine patches with AOSP fetches we can add a separate function to do just that (eg. `apply_single_patch 000x-fix-xyz.patch`).
Patches have been dropped and we now remove the entire `Android.mk` to get rid of the old method. You can see the (much more elegant) …

[Android 10] Remove backports; fix upstream bugs; local patchfiles.

---

repo_update.sh

Backport DeskClock fixes to make the alarm go off. Without this, you'll
not be woken up...
Hopefully we can remove this soon, once Google merges it to Q.

[Android-10] [TEMPORARY] DeskClock: Fix alarms not triggering.

---

repo_update.sh

Fixes https://github.com/sonyxperiadev/bug_tracker/issues/472
Another change Google "forgot" to merge into Q branches. Just like
DeskClock the API level was updated without checking notification
related logic.
Follow them by cherry picking their quickfix, until a notification
channel rework arrives.

[Android-10] [TEMPORARY] Messaging: Fix missing notifications on SMS.

---

repo_update.sh

After sonyxperiadev/local_manifests#77, this patch is no longer required.
Successfully tested and verified there were no linker errors and GPS functioned correctly.

hardware: qcom: gps: Revert removal of libprocessgroup

---

repo_update.sh

core/Build: ro.system when comparing fingerprint
ro.build.fingerprint is dynamically generated by deriveFingerprint(), but its output does not match ro.{system,vendor}.build.fingerprint.
See https://android-review.googlesource.com/c/platform/frameworks/base/+/1147496

[VERIFYME] [Android-10] fwb: Add ro.system fingerprint patch

---

repo_update.sh

hardware/qcom/media/sdm845 is an unused HAL and will be dropped from local_manifests soon.

[2/2] Remove sdm845 media

---

repo_update.sh

Not reverting "Handle updating the carrier configuration" will require a
slight change in the OSS location repo:
https://github.com/sonyxperiadev/vendor-qcom-opensource-location/pull/22
Removing the etc folder revert will remove the default qcom gps config,
allowing us to provide our own.

[WIP] gps: sdm845: Remove two reverts

---

repo_update.sh

Following PR #127, this should be in legacy branch to stop error message spam
See https://github.com/sonyxperiadev/bug_tracker/issues/470#issuecomment-535689477
and https://android-review.googlesource.com/c/platform/hardware/interfaces/+/1320090

[android-10_legacy] hardware/interfaces: Add thermal init NULL patch

---

repo_update.sh

git can still apply these patches, but using pre-rebased commits will shave off those few annoying seconds of `Performing inexact rename detection`.
---
**fwb: Drop fwb build fingerprint patches**
All devices are now on FULL_TREBLE via PRODUCT_FULL_TREBLE_OVERRIDE.
This means `ro.treble.enabled` is true, which means the fingerprint tests in fwb will be skipped in favour of a vintf compat test.
[frameworks/base/core/java/android/os/Build.java](https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-10.0.0_r33/core/java/android/os/Build.java#1046) (abridged):
```
public static final boolean IS_TREBLE_ENABLED =
SystemProperties.getBoolean("ro.treble.enabled", false);
if (IS_TREBLE_ENABLED) {
int result = VintfObject.verifyWithoutAvb();
return result == 0;
}
[...]
if …
```

fwb: Update hashes for rebased commits, drop fingerprint patches

---

repo_update.sh

This is an excerpt from #128 containing cleanups and style improvements only. All the functional work on re-entrancy has been dropped, as that needs more time and discussion (and is, for what it's worth, already a far too massive timesink). See that PR for some of the review comments and suggestions.
Most notably this introduces a new function to deduplicate pushd+LINK= logic, whose arguments are always identical except one repository.

[repo_update] Address shellcheck issues, simplify pushd+LINK logic

---

repo_update.sh

* When $OUT is on a compressed disk,
`du -k -s` might not return the correct sizes.
* Adding `-b` gets us close to the actual size.
toybox commit: https://github.com/landley/toybox/pull/177
Test: m, builds and boots.
Devices: crosshatch blueline bonito sargo (anything with dynamic partitions)

[master] repo_update.sh: releasetools: Use du -b

---

repo_update.sh

Thanks @pablomh for submitting the rebased burn-in protection patch to the original Gerrit CL! (Blame me if it breaks, I did the rebase and conflict "resolution") As well as being the guinea pig building on a compressed file system and running into annoying issues that are simply solved with `du -b` :grimacing:
@jerpelea Will you force push b676318ecf96d44aa943f28028a8a46e5ff0ac76 off or should I revert it in this PR?

[R] Update SystemUI burn-in protection patch and fix build on compressed file systems

---

repo_update.sh

We switched to the CAF HAL some time ago and don't need AOSP anymore. Drop all patches which are merely an extra burden to look at and maintain, for no gain.

[repo_update] Drop unused audio patches

---

repo_update.sh

We observe a crash on SailfishOS when playing back videos in our browser. Adding this patch solves the issue.

repo_update: add "stagefright: fix stop-error-release crash" patch.

---

repo_update.sh

This reverts commit 3f90fdcb2f8c723e3e8f981c976d7e8424719969.
The ancient Bluetooth libs are finally deprecated and disallowed from being used in Android 13; our device trees are being updated to stop using them and it is no longer needed to apply this workaround to make these modules available:
https://github.com/sonyxperiadev/device-sony-common/pull/899
For completeness the libraries weren't used for quite some time already: the configuration is only used in a fallback case when the new audio HAL is disabled by setting `persist.bluetooth.bluetooth_audio_hal.disabled` to `true` manually.

Revert "repo_update: legacy compatibility" (expose ancient Bluetooth libs)

---

repo_update.sh

This API is required by PAL (Platform Audio Layer).
This patch will be merged into AOSP, but until that
happens we should apply it here.

[android-13] repo_update: Add compress_set_codec_params API patch

---

repo_update.sh

This API is required by PAL (Platform Audio Layer).
This patch will be merged into AOSP, but until that
happens we should apply it here.
Fixes: https://github.com/sonyxperiadev/bug_tracker/issues/848

[android-14] repo_update: Add compress_set_codec_params API patch

---

repo_update.sh

The commit[1] landed in the android-15.0.0_r20 tag,
we don't need this patch anymore.
[1] https://android.googlesource.com/platform/external/tinycompress/+/4d5a622bdac3da93acee15d1a27d8aca18f00d8c

[15r20] Revert "repo_update: Add compress_set_codec_params API patch"
