repo_update.sh

* Switch to HTTPS to supress warnings
* Use pushd/popd for easier maintenance

Switch to HTTPS and use pushd/popd

---

repo_update.sh

Also check $PWD once and store the value

Allow the option to use an insecure proxy

---

repo_update.sh

Add patch to fix https://github.com/sonyxperiadev/bug_tracker/issues/25

audio: Add voicemmode call patch for msm8998 devices

---

repo_update.sh

Fix wrong reference of AOSP patch for nougat-mr1.5-release.
https://android-review.googlesource.com/#/c/platform/hardware/qcom/audio/+/535255/

[N-MR1] audio: Add voicemmode call patch for msm8998 devices

---

repo_update.sh

Signed-off-by: David Viteri <davidteri91@gmail.com>

repo_update: make our healthd work again

---

repo_update.sh

This commit fix applying "git cherry-pick 02f13da8e1d303f5b7ccbe21633e6d0cb6331868"

Fix applying GPS patches for msm8998

---

repo_update.sh

This PR is related to change request https://github.com/sonyxperiadev/bug_tracker/issues/119

Remove useless patches for Android-7.1.2_r36

---

repo_update.sh

To be merged with new ODM images that contain the appropriated prop.

repo_update: Add odm check

---

repo_update.sh

Reverts sonyxperiadev/repo_update#45

Revert "Add vold patch for exfat"

---

repo_update.sh

The following commits have been merged into AOSP:
- Add kryo support.
-> https://android-review.googlesource.com/c/platform/bionic/+/363153
- libc: use Cortex-A7/A53 memset on Kryo
-> https://android-review.googlesource.com/c/platform/bionic/+/368092
- libc: ARM: Add 32-bit Kryo memcpy
-> https://android-review.googlesource.com/c/platform/bionic/+/368092

Update bionic patches with commits merged into AOSP

---

repo_update.sh

This patch is needed to allow the night mode colour to switch

Add display HAL patch for night mode

---

repo_update.sh

They're already included in Pie.

Remove unneeded bionic patches

---

repo_update.sh

The patched code has dissapeared.

Remove unneeded frameworks/av patches

---

repo_update.sh

They were split into two sections.

Unify frameworks/base patches section

---

repo_update.sh

According to https://android-review.googlesource.com/c/platform/packages/inputmethods/LatinIME/+/469478,
the issue was solved in P Preview.

Remove unneeded packages/inputmethods/LatinIME patches

---

repo_update.sh

Thanks to @MarijnS95 for the patches!

Adapt hardware/qcom/gps patches to Pie

---

repo_update.sh

Put the frameworks/base patch in the right place.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>

[8.1.0_r3] Сode alignment and duplicate removal

---

repo_update.sh

Thanks to @alviteri for noticing it and letting me know!!

Remove stray symlink

---

repo_update.sh

PN548 is untested.
Signed-off-by: Humberto Borba <humberos@omnirom.org>

hardware: nxp: nfc: Restore PN547 and PN548 support

---

repo_update.sh

yoshinoR2 nile and tama need this for VNDK
Signed-off-by: David Viteri <davidteri91@gmail.com>

audio/gps fix build for VNDK

---

repo_update.sh

This will make it easier to understand for newcomers.
Change-ids can be pasted into AOSP gerrit, which I think is a big help.

Add comments explaining what each action does

---

repo_update.sh

For use on OLED equipped devices.

[REPO_UPDATE] Add burn-in protection for status/navbar items

---

repo_update.sh

https://android-review.googlesource.com/c/platform/hardware/qcom/audio/+/728153
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>

[master] Update audio commit description

---

repo_update.sh

https://android-review.googlesource.com/c/platform/hardware/qcom/audio/+/728153
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>

[android-9.0.0_r1] Update audio commit description

---

repo_update.sh

Check whether the commit is already stored, and only attempt to fetch it if it is not found locally.

[master] Look for commits locally before fetching

---

repo_update.sh

The commit has been merged into the latest android-10 revisions
Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

remove Fix cases without vendor/oem partition

---

repo_update.sh

Fixes unlabeled properties that would normally be labeled by `system/sepolicy/public/property_contexts`
See https://android-review.googlesource.com/c/platform/system/sepolicy/+/1185400

system/sepolicy: props: Remove compatible guard

---

repo_update.sh

Comment got accidentally included in the previous PR.
Revert for now until the new gps hal is proven working.

Revert "Update required gps patches"

---

repo_update.sh

patches are not needed since there is no dependency on aosp gps hal anymore

[DNM] Remove gps patches

---

repo_update.sh

See https://github.com/sonyxperiadev/bug_tracker/issues/470#issuecomment-535689477
and https://android-review.googlesource.com/c/platform/hardware/interfaces/+/1320090

[VERIFYME] hardware/interfaces: Add thermal init NULL patch

---

repo_update.sh

These changes still need to be cleaned up, some patches need conflict resolving and pushed to gerrit again; see this as a starting point during our R bringup.

[REPO_UPDATE] [DNM] Preliminary changes for Android R

---

repo_update.sh

exfatprogs accepts 'p' for automatic repair.

[master] Switch to exfatprogs compatible fsck parameter

---

repo_update.sh

Fixes: sonyxperiadev/bug_tracker#665

[master] repo_update: wifi_hal: Fix access check of control param file
